title: tsumarios' blog
description: >
  Cybersec and Research - A cool description might be something like "a place where I post about my research and share resources".

author:
  name: "Mario Raciti"
  email: "marioraciti@pm.me"
       
show_excerpts: true
excerpt_separator: "<!-- readmore -->"
paginate: 5
paginate_path: /page/:num/
permalink: pretty
url: https://tsumarios.github.io
baseurl: /blog
favicon: https://tsumarios.github.io/favicon.ico

header_pages:
  - about.md
  - privacy.md

highlighter: rouge
kramdown:
  syntax_highlighter: rouge  

minima:
  skin: auto

  date_format: "%b %-d, %Y"

  social_links:
    - { platform: rss, user_url: "/blog/feed.xml" }
    - { platform: github, user_url: "https://github.com/tsumarios"}
    - { platform: twitter, user_url: "https://twitter.com/tsumarios"}
    - { platform: mastodon, user_url: "https://infosec.exchange/@tsumarios", instance: infosec.exchange}
    - { platform: reddit, user_url: "https://www.reddit.com/user/zr0_day"}
    - { platform: instagram, user_url: "https://instagram.com/tsumarios"}
    - { platform: tiktok, user_url: "https://tiktok.com/@tsumarios"}
    - { platform: linkedin, user_url: "https://linkedin.com/in/marioraciti"}
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=YTUJQ1wAAAAJ"}
    - { platform: researchgate, user_url: "https://www.researchgate.net/profile/Mario-Raciti-2"}
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/12880903/tsumarios" }
    - { platform: keybase, user_url: "https://keybase.io/marioraciti"}

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jemoji
  - rouge
