title: tsumarios' blog
description: >
  Cybersec and Research - A cool description might be something like "a place where I post about my research and share resources".

author:
  name: Mario Raciti
  email: "marioraciti@pm.me"
       
show_excerpts: true
excerpt_separator: "<!-- readmore -->"
paginate: 5
paginate_path: /page/:num/
permalink: pretty
url: https://tsumarios.github.io
baseurl: /blog
favicon: https://github.com/tsumarios/tsumarios.github.io/blob/master/assets/img/icon.png

header_pages:
  - about.md
  - privacy.md

highlighter: rouge
kramdown:
  syntax_highlighter: rouge  

minima:
  skin: auto

  date_format: "%b %-d, %Y"

  social_links:
    twitter: tsumarios
    github: tsumarios
    instagram: tsumarios
    linkedin: marioraciti
    keybase: marioraciti

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jemoji
  - rouge
