title: tsumarios' blog
description: >
  CySec and Research - A cool description might be something like "a place where I post about my research and share resources".

author:
  name: "Mario Raciti"
  email: "marioraciti@pm.me"
       
show_excerpts: true
excerpt_separator: "<!-- readmore -->"
paginate: 5
paginate_path: /page/:num/
permalink: pretty
url: https://tsumarios.github.io
baseurl: /blog
favicon: https://tsumarios.github.io/favicon.ico

header_pages:
  - about.md
  - privacy.md

highlighter: rouge
kramdown:
  syntax_highlighter: rouge  

minima:
  skin: auto

  date_format: "%b %-d, %Y"

  social_links:

    - title: GitHub
      icon: github
      url: "https://github.com/tsumarios"
    - title: X (formerly Twitter)
      icon: x-twitter
      url: "https://twitter.com/tsumarios"
    - title: Mastodon
      icon: mastodon
      url: "https://infosec.exchange/@tsumarios"
    - title: Reddit
      icon: reddit
      url: "https://www.reddit.com/user/zr0_day"
    - title: Instagram
      icon: instagram
      url: "https://instagram.com/tsumarios"
    - title: TikTok
      icon: tiktok
      url: "https://tiktok.com/@tsumarios"
    - title: LinkedIn
      icon: linkedin
      url: "https://linkedin.com/in/marioraciti"
    - title: Google Scholar
      icon: google-scholar
      url: "https://scholar.google.com/citations?user=YTUJQ1wAAAAJ"
    - title: ResearchGate
      icon: researchgate
      url: "https://www.researchgate.net/profile/Mario-Raciti-2"
    - title: Stack Overflow
      icon: stack-overflow
      url: "https://stackoverflow.com/users/12880903/tsumarios"
    - title: Keybase
      icon: keybase
      url: "https://keybase.io/marioraciti"

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jemoji
  - rouge
